export const YEAR_META = {
  y2: {
    id: 'y2',
    shortLabel: 'Year 2 / 大二',
    title: 'The Foggy Exploration',
    titleZh: '迷雾探索期',
    subtitle: 'Build direction, compare routes, and turn scattered information into a realistic planning roadmap.',
    subtitleZh: '在大二阶段完成方向判断，把零散信息整理成可执行的申请规划。',
    currencyLabel: 'Coins / 金币',
  },
  y3: {
    id: 'y3',
    shortLabel: 'Year 3 / 大三',
    title: 'The Astral Sprint',
    titleZh: '星轨冲刺期',
    subtitle: 'Execute the application season with stronger materials, clearer timing, and calmer decision making.',
    subtitleZh: '在大三阶段进入申请执行期，用更清晰的材料、时间线和策略完成冲刺。',
    currencyLabel: 'Gems / 宝石',
  },
}

const levelDefinitions = {
  y2: [
    {
      id: 1,
      mapNode: 1,
      name: 'Identity Forge',
      nameZh: '身份锻炉',
      mapLabel: '身份 / Identity',
      title: 'Y2-1: Identity Forge',
      titleZh: 'Y2-1：身份锻炉',
      file: 'year2_1.vue',
      rewardCoins: 20,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Define your starting applicant profile so later planning choices have a clear point of reference.',
        summaryZh: '先明确你的申请者起点，让后续所有规划选择都有参照对象。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'How to summarize your current style, strengths, and visible identity as an applicant.',
        learnBodyZh: '如何概括自己的申请风格、优势和可见标签，形成清晰的申请者画像。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Create a simple applicant profile card before doing route selection or school tiering.',
        realTaskBodyZh: '在地区选择和选校分层之前，先建立一张自己的申请者基础信息卡。',
        mechanics: [
          { term: '学习原型 / Study Archetype', meaning: 'represents your planning style and narrative angle in future materials.' },
          { term: '角色外观 / Avatar look', meaning: 'gives you visible live feedback so your planning identity feels concrete, not abstract.' },
          { term: '随身工具 / Familiar tool', meaning: 'stands for the strength you tend to rely on when solving application problems.' },
        ],
        help: '先完成姓名、学习原型、发色、服装和工具，再封印身份。/ Finish all five choices before sealing your identity.',
      },
    },
    {
      id: 2,
      mapNode: 2,
      name: 'Region Choice',
      nameZh: '地区罗盘',
      mapLabel: '地区 / Region',
      title: 'Y2-2: Region Choice',
      titleZh: 'Y2-2：地区罗盘',
      file: 'year2_2.vue',
      rewardCoins: 30,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Compare major study-abroad routes and choose a direction that fits your goals, budget, timeline, and preferred outcomes.',
        summaryZh: '比较主要留学路径，根据目标、预算、时间和发展方向做地区判断。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'The broad differences between Hong Kong, Singapore, the UK, the US, and Europe / EU mainland.',
        learnBodyZh: '了解中国香港、新加坡、英国、美国与欧洲大陆路线之间的核心差异。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Choose the route families you want to prioritize before collecting programs.',
        realTaskBodyZh: '在搜集项目之前，先确定你优先考虑的地区路线。',
        mechanics: [
          { term: '传送门 / Portal route', meaning: 'stands for a real destination region and its study or work pathway.' },
          { term: '路线共鸣 / Route resonance', meaning: 'means your answers align with that region’s cost, duration, and opportunity structure.' },
        ],
        help: '每次选择都会强化某条地区路径，最后会得到你的优先路线建议。/ Each answer strengthens one route, leading to a recommended pathway.',
      },
    },
    {
      id: 3,
      mapNode: 3,
      name: 'Tier Mapping',
      nameZh: '选校分层',
      mapLabel: '选校 / Tiering',
      title: 'Y2-3: Tier Mapping',
      titleZh: 'Y2-3：选校分层',
      file: 'year2_3.vue',
      rewardCoins: 30,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Learn to distribute schools across reach, target, and safety tiers instead of applying with one unrealistic cluster.',
        summaryZh: '学会把院校分成冲刺、主申和保底，而不是只押一个不稳的区间。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'Why tiering matters, what a balanced list looks like, and how profile realism affects school choices.',
        learnBodyZh: '理解为什么要做分层申请，什么是平衡名单，以及个人背景如何影响定位。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Build the first draft of a rational school list.',
        realTaskBodyZh: '完成第一版合理的选校名单分层。',
        mechanics: [
          { term: '命运天平 / Scales of destiny', meaning: 'represent the balance between ambition, fit, and security in your school list.' },
          { term: '学院卡牌 / School cards', meaning: 'stand for real program choices that must be placed by probability, not emotion alone.' },
        ],
        help: '拖动所有院校卡片后再提交。/ Drag every school card into a tier before submitting.',
      },
    },
    {
      id: 4,
      mapNode: 4,
      name: 'Major Recipe',
      nameZh: '专业配方',
      mapLabel: '专业 / Major',
      title: 'Y2-4: Major Recipe',
      titleZh: 'Y2-4：专业配方',
      file: 'year2_4.vue',
      rewardCoins: 25,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Connect your background ingredients to a coherent major direction.',
        summaryZh: '把你的背景条件与目标专业方向对应起来。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'How coursework, projects, internships, and interests combine into a credible major story.',
        learnBodyZh: '课程、项目、实习和兴趣如何组合成可信的专业申请故事。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Decide which major direction is strategically consistent with your profile.',
        realTaskBodyZh: '判断哪个专业方向与你的背景更匹配。',
      },
    },
    {
      id: 5,
      mapNode: 5,
      name: 'Action Plan',
      nameZh: '行动点分配',
      mapLabel: '行动 / Action',
      title: 'Y2-5: Action Plan',
      titleZh: 'Y2-5：行动点分配',
      file: 'year2_5.vue',
      rewardCoins: 35,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Practice allocating limited time and energy to the activities with the highest application value.',
        summaryZh: '练习把有限的时间和精力分配给最有申请价值的事情。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'How to weigh GPA, language exams, projects, internships, research, and information gathering by ROI.',
        learnBodyZh: '学会按投入产出比判断 GPA、语言、项目、实习、科研和信息搜集的优先级。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Draft a real semester-level effort allocation plan.',
        realTaskBodyZh: '完成一版真实可执行的学期精力分配方案。',
        mechanics: [
          { term: '行动点 / Action points', meaning: 'represent limited weekly time, energy, and attention.' },
          { term: '星尘投入 / Stardust allocation', meaning: 'stands for committing your resources to one growth area instead of spreading too thin.' },
        ],
        help: '必须把 10 点全部分配完，系统才会给出分析。/ Spend all 10 points before requesting feedback.',
      },
    },
    {
      id: 6,
      mapNode: 6,
      name: 'Case Search',
      nameZh: '案例档案',
      mapLabel: '案例 / Cases',
      title: 'Y2-6: Case Search',
      titleZh: 'Y2-6：案例档案',
      file: 'year2_6.vue',
      rewardCoins: 25,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Read past cases critically instead of copying them blindly.',
        summaryZh: '学会带着判断阅读案例，而不是机械照搬。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'How to extract pattern, profile fit, and decision clues from past application cases.',
        learnBodyZh: '从案例中提取背景匹配度、路径规律和决策线索。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Use reference cases to calibrate your expectations and next actions.',
        realTaskBodyZh: '通过案例校准自己的预期和下一步行动。',
      },
    },
    {
      id: 7,
      mapNode: 7,
      name: 'Final Trial',
      nameZh: '年终试炼',
      mapLabel: '终测 / Trial',
      title: 'Y2-7: Final Trial',
      titleZh: 'Y2-7：年终试炼',
      file: 'year2_7.vue',
      rewardCoins: 40,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Consolidate the Year 2 planning logic before entering the application-execution stage.',
        summaryZh: '在进入正式申请执行期前，巩固大二阶段的规划逻辑。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'How route choice, school tiering, profile building, and resource allocation fit together.',
        learnBodyZh: '把地区判断、选校分层、背景打造和资源分配串成完整逻辑。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Check whether your Year 2 planning foundation is stable enough for Year 3 execution.',
        realTaskBodyZh: '检查你的大二规划基础是否足够支撑大三申请执行。',
      },
    },
  ],
  y3: [
    {
      id: 1,
      mapNode: 1,
      name: 'Timeline',
      nameZh: '申请时间线',
      mapLabel: '时间 / Timeline',
      title: 'Y3-1: Crucible of Truth',
      titleZh: 'Y3-1：时间熔炉',
      file: 'year3_1.vue',
      rewardCoins: 30,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Understand the order of key application tasks so you do not miss critical deadlines.',
        summaryZh: '理解申请任务的时间顺序，避免关键节点错位。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'How to sequence exams, materials, references, and submissions across the season.',
        learnBodyZh: '学会安排语言考试、材料撰写、推荐信和网申提交的先后关系。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Create a reliable Year 3 application timeline.',
        realTaskBodyZh: '建立一条可靠的大三申请时间线。',
      },
    },
    {
      id: 2,
      mapNode: 2,
      name: 'Material Types',
      nameZh: '材料分工',
      mapLabel: '材料 / Materials',
      title: 'Y3-2: Bureau of Magic',
      titleZh: 'Y3-2：材料鉴定局',
      file: 'year3_2.vue',
      rewardCoins: 30,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Learn the distinct jobs of CV, PS, and RL so your application materials stop repeating each other.',
        summaryZh: '理解 CV、PS、RL 各自的功能，避免材料之间互相重复或放错位置。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'Which content belongs to factual record, personal motivation, or third-party endorsement.',
        learnBodyZh: '区分客观经历、个人动机和第三方评价分别应该放在哪份材料里。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Classify application content into the right document bucket.',
        realTaskBodyZh: '把申请内容准确分配到对应材料中。',
        mechanics: [
          { term: '封印印章 / Stamps', meaning: 'represent deciding which document should carry a specific piece of evidence.' },
          { term: '驳回提示 / Rejection modal', meaning: 'shows why a statement is misplaced and what the correct document function is.' },
        ],
        help: '阅读纸张内容后，再选择 CV / PS / RL 印章。/ Read the statement first, then stamp it as CV, PS, or RL.',
      },
    },
    {
      id: 3,
      mapNode: 3,
      name: 'CV Surgery',
      nameZh: '简历诊疗',
      mapLabel: '简历 / CV',
      title: 'Y3-3: Clinic of Truth',
      titleZh: 'Y3-3：简历诊疗室',
      file: 'year3_3.vue',
      rewardCoins: 30,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Turn a noisy CV into a concise, evidence-driven profile document.',
        summaryZh: '把杂乱的简历改造成清晰、结果导向的申请文档。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'How to cut filler, keep evidence, and foreground impact in a CV.',
        learnBodyZh: '学会删掉空话、保留证据，用结果导向写法呈现简历。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Refine your resume into a stronger screening document.',
        realTaskBodyZh: '把你的简历打磨成更强的初筛材料。',
      },
    },
    {
      id: 4,
      mapNode: 4,
      name: 'PS Weaving',
      nameZh: '文书编织',
      mapLabel: '文书 / PS',
      title: 'Y3-4: Constellation of Memories',
      titleZh: 'Y3-4：记忆星图',
      file: 'year3_4.vue',
      rewardCoins: 30,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Build a PS that links past experience, present motivation, and future direction.',
        summaryZh: '构建一篇能连起过去经历、现在动机和未来方向的 PS。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'How narrative structure works in a personal statement.',
        learnBodyZh: '理解个人陈述中的叙事结构与逻辑推进。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Shape the backbone of your personal statement.',
        realTaskBodyZh: '搭建个人陈述的核心叙事骨架。',
      },
    },
    {
      id: 5,
      mapNode: 5,
      name: 'Recommendation',
      nameZh: '推荐信沟通',
      mapLabel: '推荐 / RL',
      title: 'Y3-5: Tsundere Mentor',
      titleZh: 'Y3-5：推荐信沟通',
      file: 'year3_5.vue',
      rewardCoins: 25,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Learn how to request recommendation letters with clarity and respect.',
        summaryZh: '学会清晰、礼貌地推进推荐信沟通。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'How to give referees enough information and reduce back-and-forth confusion.',
        learnBodyZh: '学会如何为推荐人提供足够信息，减少沟通摩擦。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Handle recommendation-letter communication more professionally.',
        realTaskBodyZh: '以更专业的方式推进推荐信请求与跟进。',
      },
    },
    {
      id: 6,
      mapNode: 6,
      name: 'Exam Combat',
      nameZh: '申请季战斗',
      mapLabel: '冲刺 / Battle',
      title: 'Y3-6: The Dark Citadel',
      titleZh: 'Y3-6：暗堡冲刺战',
      file: 'year3_6.vue',
      rewardCoins: 40,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Translate application-season pressure into concrete strategic actions instead of panic.',
        summaryZh: '把申请季压力转化为具体策略动作，而不是被焦虑牵着走。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'How to choose between language prep, essay polishing, outreach, recovery, and deadline handling under pressure.',
        learnBodyZh: '学会在压力下判断语言备考、文书打磨、沟通联系、恢复节奏和截止任务的优先级。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Practice decision making during the busiest months of application season.',
        realTaskBodyZh: '模拟申请季最繁忙阶段的策略选择。',
        mechanics: [
          { term: '外教精修斩 / Proofreader’s Slash', meaning: 'means using editing support to strengthen essays fast and precisely.' },
          { term: '套磁护盾 / Cold Email Shield', meaning: 'stands for proactive outreach, mentor contact, or communication that reduces later risk.' },
          { term: '冰美式 / Iced Americano', meaning: 'represents recovery, pacing, and functional self-care during heavy deadlines.' },
        ],
        help: '先看关卡说明，再决定何时爆发输出、何时保命、何时恢复。/ Read the stage explanation first, then decide when to burst, defend, or recover.',
      },
    },
    {
      id: 7,
      mapNode: 7,
      name: 'Evade Traps',
      nameZh: 'DIY避坑',
      mapLabel: '避坑 / Risk',
      title: 'Y3-7: DIY Bog Sweeper',
      titleZh: 'Y3-7：DIY避坑沼泽',
      file: 'year3_7.vue',
      rewardCoins: 25,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Spot common DIY application mistakes before they become real damage.',
        summaryZh: '提前识别 DIY 申请中常见的失误点。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'Which mistakes are easy to miss in self-managed applications and how to recover.',
        learnBodyZh: '理解自助申请中最容易忽视的错误与修正方式。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Check your process for avoidable risks.',
        realTaskBodyZh: '检查自己的申请流程中有哪些可避免的风险。',
      },
    },
    {
      id: 8,
      mapNode: 8,
      name: 'Coronation',
      nameZh: '终章加冕',
      mapLabel: '加冕 / Offer',
      title: 'Y3-8: The Astral Coronation Hall',
      titleZh: 'Y3-8：星穹加冕厅',
      file: 'year3_8.vue',
      rewardCoins: 50,
      guide: {
        eyebrow: '本关学习目标 / Learning Goal',
        summary: 'Review the full application journey and understand what your preparation has led to.',
        summaryZh: '回顾完整申请旅程，理解自己的准备最终带来了什么结果。',
        learn: '你将学会什么 / What you will learn',
        learnBody: 'How the Year 2 foundation and Year 3 execution connect into final outcomes.',
        learnBodyZh: '理解大二规划基础与大三执行动作如何共同影响最终结果。',
        realTask: '本关对应的真实申请任务 / Real-world application task',
        realTaskBody: 'Reflect on your application process and outcomes.',
        realTaskBodyZh: '复盘自己的申请过程与结果。',
      },
    },
  ],
}

export const LEVEL_DEFINITIONS = levelDefinitions

export const createInitialLevels = (year) => (
  (levelDefinitions[year] || []).map((level, index) => ({
    ...level,
    unlocked: index === 0,
    completed: false,
    skipped: false,
  }))
)

export const getLevelDefinition = (year, levelId) => (
  levelDefinitions[year]?.find((level) => level.id === levelId) ?? null
)

export const getYearMeta = (year) => YEAR_META[year] ?? null
